{
 "title": "Cusotom monitoring",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [
  "docker",
  "host"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes * 100"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes" }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}